name: flutter_artifactsmmo_client
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: modules/domain
  di:
    path: modules/di

  home_feature:
    path: modules/features/home_feature

dev_dependencies:
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env_prod
    - assets/images/maps/
    - assets/images/characters/
