name: flutter_artifactsmmo_client
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
