name: home_feature
publish_to: "none"

environment:
  sdk: ">=3.3.4"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  di:
    path: ../../di

dev_dependencies:
  flutter_lints: 3.0.1
